### PR TITLE
Add support for the robust-externalize package

### PR DESCRIPTION
**Pull request by jlelong**
#77

### CODE REVIEW

**Comment by jlelong** [comment]
@dflvunoooooo I have made a first attempt to support robust-externalize.
Could you test? The easiest way to proceed is to copy the file `syntaxes/LaTeX.tmLanguage.json` (not the one in `syntaxes/data`!) to the `syntax` directory of your LaTeX-Workshop extension after making a backup of the original file to revert the changes afterwards.
Looking forward to here from you

**Comment by dflvunoooooo** [comment]
Wow, great! This is awesome. Thank you for your work! You even provided syntax highlighting for the code inside :) 

It is already working perfect for simple CacheMeCode environments. The only problem I found so far happens, when CacheMeCode is inside another, for example a figure, environment. Then the syntax highlighting does not revert back to normal.

Screenshot_20240322_140346

´´´
\documentclass{scrartcl}


\usepackage{robust-externalize}
\usepackage{gnuplot-lua-tikz}

\begin{filecontents}{test.dat}   
    0.0000 0.0
    1.0000 1.0
    2.0000 2.0
    3.0000 3.0
\end{filecontents}

% Define new preset to save python as pgf.
\robExtConfigure{
    new preset={python matplotlib pgf}{
        python,
        include command is input,
        custom include command={\input{\robExtAddCachePathAndName{\robExtFinalHash.pgf}}},
    },
}

\begin{document}

Woring for simple gnuplot environment. Even with syntax highlighting for python! :) 
\begin{CacheMeCode}{gnuplot, tikz terminal}
plot 'test.dat' using 1:($2-1)
\end{CacheMeCode}

Same for python. It is even working if a self defined preset is used! :)
\begin{CacheMeCode}{python matplotlib pgf, set placeholder eval={__BREITE__}{\lenToCmNoUnit[in]{\textwidth}}, set placeholder eval={__HOEHE__}{\lenToCmNoUnit[in]{.71\textwidth}}}
    import matplotlib.pyplot as plt
    import matplotlib 
    matplotlib.use("pgf")
    plt.rcParams.update({
        "figure.figsize": "__BREITE__, __HOEHE__",
    })
    year = [2014, 2015, 2016, 2017, 2018, 2019]
    tutorial_count = [39, 117, 111, 110, 67, 29]
    plt.plot(year, tutorial_count, color="#6c3376", linewidth=2)
    plt.title("Simple plot")
    plt.xlabel('Year')
    plt.ylabel('Number of futurestud.io Tutorials')
    plt.savefig(get_filename_from_extension(".pgf"), bbox_inches="tight")
\end{CacheMeCode}

Problem if CacheMeCode is inside another environment. Atleast inside a figure.
\begin{figure}
    \centering
    \begin{CacheMeCode}{gnuplot, tikz terminal}
        plot 'test.dat' using 1:($2-1)
    \end{CacheMeCode}
    % From here on, the highlighting of normal Latex does not work anymore. 
    \caption{Test}%
    \label{py:Test}
\end{figure}

Test Text to check synay highlighting.

\end{document}
´´´

**Comment by dflvunoooooo** [comment]
Fix is working! :)

**Comment by dflvunoooooo** [comment]
This is really awesome, thank you very much!

**Comment by jlelong** [comment]
Before merging this PR, I would like to make the list of supported languages make sense.

@dflvunoooooo I had a close look at the documentation and I have the impression hat it does not make sense to include `html`, `xml` and `yaml`. Do you confirm? What about the other languages listed above? I should also add tikz because for the time being its content is considered as verbatim; which is probably not really helpful to type it.

**Comment by dflvunoooooo** [comment]
In generell you are right, but there is a feature of robust-extrenalize called "print code and result" which uses listings, I think. With that you can print the code and the result. I think it would be nice, if every language would be supported. Is that a problem or more work? But tikz would be great, if the highlighting of tikz is different then that of latex?

**Comment by jlelong** [comment]
Thanks for the clarification. So, I am keedping all the languages currently listed in my post above (this part of the syntax file is generated by a script so adding more languages has no impact on the maintenance). For all other languages, the content of the robust-externalize environment is considered as verbatim. So, we need to make something special for the `tikz` case to make sure it is highlighted as latex code.

**Comment by dflvunoooooo** [comment]
I am not sure this is necessary. The highlighting of tikz inside a CacheMe environment is working.

Screenshot_20240323_150109

**Comment by jlelong** [comment]
This is because the `CacheMe` environment was not in my list. I only considered `CacheMeCode`, `PlaceholderPathFromCode`, `PlaceholderFromCode`, `SetPlaceholderCode`.  I am adding it.

But then I am wondering about the `[scale=0.7]` option parameter. Should all these environment accept an optional parameter, which can maybe be split over several lines? Currently, the optional parameter breaks the highlighting.

**Comment by dflvunoooooo** [comment]
I see, CacheMe wasn't mentioned before, sorry for that. Thank you. 

I don't think everyr environment accept options in [] and less so over several lines. But, I don't know for sure. I will reach out to the author.

**Comment by dflvunoooooo** [comment]
Now, that you want to catch tikz. There is also the 
```
begin{tikzpictureC}[baseline=(A.base)]
…
\end{tikzpictureC}
```
environment for a cached tikz picture.

**Comment by jlelong** [comment]
There is nothing to do for `tikzpictureC` because it is already handled by the LaTeX as a general environment since its content is LaTeX.

**Comment by dflvunoooooo** [comment]
Did you set the CacheMe environment the same way as the CacheMeCode environment? CacheMe can cache "TikZ, LATEX, python, and much, more", according to the manual. I am not sure what the difference between CacheMeCode and CacheMe are.

**Comment by jlelong** [comment]
I set all the environments the same way so that they recognize all the languages.

**Comment by dflvunoooooo** [comment]
Perfekt!

**Comment by tobiasBora** [comment]
Hi, thanks a lot for your work! 

So regarding the languages, by default we support python, latex, gnuplot, and bash, but the users can very easily define their own presets to support more languages… so the more the better I guess ^^

Regarding the difference between `CacheMeCode` and `CacheMe`, the presence of `Code` at the end means that LaTeX parses the code in a more complicated, verbatim, manner: it allows user to specify characters that would be forbidden/removed in a normal environment : for instance, % are comments in LaTeX, and are therefore removed in CacheMe but are kept in CacheMeCode, same, newlines are removed etc. On the other hand, due to how LaTeX works, these environments cannot be contained into macro parameters like `\fbox{…}` and inside some environments like `align`. So users would typically use `CacheMe` when the environment contains simple latex code, and `CacheMeCode` otherwise. For this reason, I don't think it it really necessary to support non-latex syntax highlighting inside `CacheMe`.

Also, I'm planning to introduce very soon a command `\cacheMeCode[preset options]{code}` having the same syntax as `\cacheMe` but, again, for non-latex code, you might want to support it as well.

> But then I am wondering about the [scale=0.7] option parameter. 

This is not an option that is part of CacheMe, but this is part of the content of the environment: the `tikzpicture` preset will automatically write `\begin{tikzpicture}` in the file, so `[scale=0.7]` (and everything that follows) is just happened after, so it creates at the end `\begin{tikzpicture}[scale=0.7]`, but for instance the `latex` preset does not assume anything like that.

**Comment by jlelong** [comment]
@tobiasBora Thanks a lot for your detailed explanations. 

> For this reason, I don't think it it really necessary to support non-latex syntax highlighting inside `CacheMe`.

I use the same rules for all the environments `CacheMe`, `CacheMeCode`, `PlaceholderPathFromCode`, `PlaceholderFromCode`, `SetPlaceholderCode`. So any language supported by one of them is supported by all at the same cost.

None of these environments are optional parameters (in the LaTeX sense). In the case of `tikzpicture`, the optional parameter if any is already handled by the LaTex grammar.

For the time being, this PR only plans to support the environment mentioned above. As you are mentioning `\cacheMeCode[preset options]{code}`, are there other commands that should supported too? If so, I will make a new PR as commands are handled by completely different rules.

**Comment by tobiasBora** [comment]
> I use the same rules for all the environments

Ok thanks. I'm just wondering, if you cannot infer a language from the preset name you will fallback to verbatim right? This make sense for all *Code environments, but would it be possible to fallback to latex for the `CacheMe` one, as the user is anyway not really supposed to type non-latex code inside, and might create custom preset names that do not start with `latex`?

**Comment by jlelong** [comment]
> If you cannot infer a language from the preset name you will fallback to verbatim right? 

Yes.

If the `CacheMe` environment should only contain LaTeX code, the simplest approach is to remove it from the current PR and let it handle by the standard LaTeX grammar. Its is just yet an other environment taking a mandatory and an optional argument. It is already parsed properly.

**Comment by jlelong** [comment]
In case you are using VS Code, could you test the this PR?

The easiest way to proceed is to copy the file `syntaxes/LaTeX.tmLanguage.json` (not the one in `syntaxes/data`!) from this PR to the syntax directory of your LaTeX-Workshop extension after making a backup of the original file to revert the changes afterwards.

**Comment by tobiasBora** [comment]
> If the CacheMe environment should only contain LaTeX code, the simplest approach is to remove it from the current PR

I think it is the best solution. This way if the user gets weird syntax highlighting, they will understand they used the wrong environment. Thanks!

> In case you are using VS Code, could you test this PR?

I am not a VS Code user myself, and I'll be really busy the next 3 weeks, but if I find some time I can try to install VS code and test your changes. But @dflvunoooooo is certainly more familiar with VS code than me ^^ Thanks for your work!

**Comment by dflvunoooooo** [comment]
I was right now testing :D As far as I can see,  `CacheMe` is highlighted like Latex regardless of the option behind it, `CashMeCode` is reflecting the language if a recognisable language is given. `PlaceholderPathFromCode`, `SetPlaceholderCode` and `PlaceholderFromCode` are regarded as verbatim, is how it is intended? 

There is a problem with `PlaceholderFromCode`, like there was with `CashMeCode` at the beginning. Maybe it is also because of indention. 

Screenshot_20240325_095742

**Comment by dflvunoooooo** [comment]
Never mind! It was a missing bracket, sorry. Now everything is working as expected :)

**Comment by tobiasBora** [comment]
Oh I see… but then, note that `CacheMeCode` waits as first argument preset options like `python flavor X, blabla`, but all the `Placeholder*` and `SetPlaceholder*` command expects the name of a placeholder (think, variable) where the code should be stored. Since this code should be used later in other presets (sometimes, with even different presets), it makes no sense to specify a placeholder at that step. Unfortunately, the placeholder names are expected to start and end with two underscores, like in `__PYTHON_TMP__`, and are typically written in upper case letters. So I'm not sure how you do your parsing of this argument, but for it to work in that case as well, you certainly want:

1. to convert this string to lower case letter so that the check is not disturbed by `PYTHON` instead of `python`
2. to check if the language is part of the string, and not at the beginning

I guess if you follow the same for `CacheMeCode`, it would also be cool, this way it would also recognize stuff like `\begin{CacheMeCode}{my python preset, blabla}`.

**Comment by jlelong** [comment]
Then, I suggest the following regex to recognize the python language for instance: `/(__|[a-Za-z\s]*)python/i` (case insensitive match). It should consist of `__` or any number of words followed by the language name (case insensitive).

**Comment by dflvunoooooo** [comment]
Tested. This seems not to be working. If python is at the beginning it is working, but if python is somewhere else it is not.
Screenshot_20240325_140614

And to be clear about `PlaceholderPathFromCode`, it should be treated as verbatim? Because it is not, it is highlighted as latex code.
Screenshot_20240325_140629

Should the preset names with double underscore and in capital also work if the reflect a language anywhere? Because they do not.
Screenshot_20240325_140642

**Comment by tobiasBora** [comment]
> Then, I suggest the following regex 

Ahah, I would have taken a much more stupid regex like `.*python.*`, (and same for all languages), but I guess this should work as well! (well, according to @dflvunoooooo  it is not, not sure why)

> does only PlaceholderPathFromCode accept an option in [] at this position?

Hum, so before update 2.7, yes. Starting from the quite recent 2.7, it can actually accept now two optional arguments at that position, and `PlaceholderFromCode` can also accept now an optional argument. So to sum up, as of 2.7, it accepts:
- `CacheMeCode`: just one mandatory argument
- `PlaceholderPathFromCode`: one optional star, two optional arguments, one mandatory argument
-  `PlaceholderFromCode` and `SetPlaceholderCode`: one optional star, one optional argument, one mandatory argument

I'm also thinking that all the above environments have an equivalent environment that starts with `RobExt` like `RobExtCacheMeCode`. The user is often not expected to use it, but I created it in case of conflicts, for instance if another lib is using a command called `CacheMe`. If it's no too much burden, you can also add them, but it should be fairly rare to see user use them. I mostly use it inside the code of my own library to have a more robust code.

**Comment by jlelong** [comment]
@dflvunoooooo I am a bit puzzled by your screenshots. Everything seems fine on my side, except the optional arg in `PlaceholderPathFromCode`.

Capture d’écran 2024-03-25 à 18 11 16

@tobiasBora adding the prefix `RobExt` is fairly easy. I will do. However it is complicated to accept different numbers of optional arguments depending on the name of the environment. The only way to do is the create different matching rules and it has to be repeated for every accepter embedded language. This is can be done by a script but it adds a lot more lines to the grammar file. As a workaround, I suggest to make the grammar more permissive: accept one optional star, two optional arguments and one mandatory argument for every environment. Is it reasonable to consider that the optional arguments are not split over several lines (it makes the parsing for easier)?

**Comment by tobiasBora** [comment]
> As a workaround, I suggest to make the grammar more permissive: accept one optional star, two optional arguments and one mandatory argument for every environment.

Great. And it might actually be helpful in case I update later the syntax :-P

> Is it reasonable to consider that the optional arguments are not split over several lines

Yes. This might not be true for the macro version `\cacheMe[preset options]{content}` but here one can definitely live with single line optional arguments.

**Comment by tobiasBora** [comment]
The `preset options` are basically the same, this is just a mater of preference between environments or macros. The `preset options` can have a very diverse form (basically they are just pgf style that need to define a number of macros when executed). For instance, it is valid to write:
```
\begin{CacheMeCode}{
  set template={__MY_TEMPLAE__},
  set compilation command={python "__ROBEXT_SOURCE_FILE__"},
}
# some python code generating an image
\end{CacheMeCode}
```

But most of the time, users will create a preset containing all these rules, like:
```
\robExtConfigure{
  new preset={my python}{
    set template={__MY_TEMPLAE__},
    set compilation command={python "__ROBEXT_SOURCE_FILE__"},
  },
}
```
and later just type:
```
\begin{CacheMeCode}{my python}
# some python code generating an image
\end{CacheMeCode}
```
For preset created by our library, we do follow the above naming rule. For user-defined presets, nothing prevents them from calling `my python` a preset that configures a Java environment… but it is their problem then :-P

**Comment by tobiasBora** [comment]
Note also that I plan to put when I have a bit of time a preset for sagemath called like `sage *`, not sure if you parse it as python or if you have a special language for that one.

**Comment by dflvunoooooo** [comment]
> @dflvunoooooo I am a bit puzzled by your screenshots. Everything seems fine on my side, except the optional arg in PlaceholderPathFromCode. 

Yes, there was probably something wrong with my file. I downloaded anew and it is working :) Except for the optional [] argument.

**Comment by jlelong** [comment]
> Note also that I plan to put when I have a bit of time a preset for sagemath called like `sage *`, not sure if you parse it as python or if you have a special language for that one.

Sage is parsed as python. Could you explain (in terms of parsing) what you call a preset for sagemath called like `sage *`?

**Comment by tobiasBora** [comment]
I just meant that people will call for instance
```
\begin{CacheMeCode}{sage plot, blabla}
Sage code
\end{CacheMeCode}
```
So same parsing as for other languages  except that the nae of the language is sage instead of python/…. Also, we support bash, but I don't think you listed in your above list of languages.

**Comment by jlelong** [comment]
I believe that all the environments are properly supported now. Could you confirm that?
I will a separate PR for commands afterwards.

**Comment by dflvunoooooo** [comment]
Seems to be working fine :) 

You could add gnuplot to the test:
```
\begin{figure}
    \centering
    \begin{CacheMeCode}{gnuplot}
        plot sin(x)
    \end{CacheMeCode}
\end{figure}
```

**Comment by jlelong** [comment]
I do not have the gnuplot extension on my VS Code installation, which breaks the test. Anyway, if it works for one language, it will for others too as the grammar file is generated by a script.

**Comment by tobiasBora** [comment]
Awesome, thanks a lot for your work!

**Comment by dflvunoooooo** [comment]
Yes, great work, thanks a lot!

**Pull request merged**
