### PR TITLE
Use wordPattern inspired from the markdown extension

### LINKED ISSUE #17: Occurrence highlighting and suggestions does not work well with specific characters
Originally posted by @Yarakashi-Kikohshi in James-Yu/LaTeX-Workshop#3198

This problem occurs even when extension is not enabled, but I am posting this because even if VS Code will be fixed, extension may still cause configuration overrides. I also believe that this issue can be addressed even from the extension side.

I already submitted this issue once to VS Code repository ([\# 144913][144913]). Apparently, this kind of problem may depend on `wordPattern`.

[144913]: https://github.com/microsoft/vscode/issues/144913

> https://github.com/microsoft/vscode/issues/144913#issuecomment-1066468990

If so, the following points need to be changed.

https://github.com/James-Yu/LaTeX-Workshop/blob/master/syntax/latex-language-configuration.json#L114

In addition, VS Code default Markdown does not have this problem, so it may be possible to refer to Markdown configuration.

## Occurrence highlighting and suggestions do not work well with specific characters

If there are symbols used as punctuation in Japan, occurrence highlighting and suggestions will not work well.

As an example, I gave some demonstrations to the following sentence.

```
こんにちは．先生
```

`．` is representative; similar problems can arise even with `、` and `。`. I don't have a list of punctuation marks like these, so I don't know all of them.

## Demo 1: Occurrence highlighting

The entire text will be shaded. Should be separated by `．`.

Place the cursor

## Demo 2: Suggestion

Continue to type lestters and call suggestions (`Ctrl+Space`). In advance, I created `先生` and `teacher` as a snippet.

```json
{
  "Teacher in Japanese": {
    "prefix": "せんせい",
    "body": "先生",
    "description": "先生: Teacher in Japanese"
  },
  "Teacher in English": {
    "prefix": "teacher",
    "body": "Teacher",
    "description": "Teacher in English"
  }
}
```

Suggestions are not displayed. Even if you press `Ctrl+Space`, `No suggestions` are displayed.

suggestions

## Version

- LaTeX Workshop: 8.23.0
- VS Code

    ```
     Version: 1.65.2 (user setup)
      Commit: c722ca6c7eed3d7987c0d5c3df5c45f6b15e77d1
        Date: 2022-03-10T14:33:55.248Z
    Electron: 13.5.2
    Chromium: 91.0.4472.164
     Node.js: 14.16.0
          V8: 9.1.269.39-electron.0
          OS: Windows_NT x64 10.0.19043
    ```

### PR DESCRIPTION
**Pull request by jlelong**
Related to microsoft/vscode/issues/144913

@Yarakashi-Kikohshi Could you test this new `wordPattern`?

Close #17

### CODE REVIEW

**Comment by Yarakashi-Kikohshi** [comment]
@jlelong 

I'm a user of VS Code and LaTeX Workshop, but I don't know how to test this pull request works. I'm sorry, this is my lack of knowledge.

If you can show me a detailed way to test that it works, I can test that it works.

----------

On the other hands, although this is an unusual method, I have made edits `wordPattern` in `~\.vscode\extensions\james-yu.latex-workshop-8.23.0\syntax\latex-language-configuration.json` in currently installed LaTeX Woskrhop (8.23). In this case, the problem discussed in https://github.com/microsoft/vscode/issues/144913 don't seem to arise.

**Comment by jlelong** [comment]
You can actually directly edit `~\.vscode\extensions\james-yu.latex-workshop-8.23.0\syntax\latex-language-configuration.json` as you did but note that the `wordPattern` used by LaTeX-Workshop and vscode basic LaTeX support are slightly different (in LW, we include `...`, `__` and `**` because they are snippet prefixes)

In you want to directly test this PR, 
- clone https://github.com/jlelong/vscode-latex-basics.git and checkout the branch `17-wordpattern`
    ```
    git clone https://github.com/jlelong/vscode-latex-basics.git
    git checkout -b 17-wordpattern origin/17-wordpattern
    ```
- In VS Code, press <kbd>F5</kbd> (or run `Debug: Start Debugging` from the command palette) and a new window will pop up where you can test the extension.

**Comment by Yarakashi-Kikohshi** [comment]
@jlelong, Thanks for the very clear explanation. I was able to test it successfully. I hope this test will be useful.

I tested with all extensions disabled.

## Summary

- Occurrence highlighting
    - [ ] If the following characters and full-width space is on the left, the highlight does not show.

        ```
        ＃＄％＆＝～＾｜＜＞；：・￥＠＿＋＊　
        ```

        See gif of `、`, `。`, `＝` and `～` tested as representative:

        ![sample][occurrencehighlighting]

- Suggestion
    - [x] Snippet works fine.
        - Snippets are not suggested immediately after strings, but this is normal behaviour.
    - [x] Snippet works fine in tabstops in snippet.

[occurrencehighlighting]: https://user-images.githubusercontent.com/75878492/159139268-fa7b88c4-e822-434d-a05e-0f777e00a566.gif

## Test procedure

Note that these tests only consider Ascii characters and Japanese at best. There are numerous languages in the world, but only two have been tested.

1. I have drawn up lists of "the patterns in which suggestions are displayed" and "the characters immediately preceding the pattern in which suggestions are displayed".
2. I have tested all the patterns from each of the two lists.
3. Visually check Suggestion display and Occurrence highlighting.

### list of the patterns in which suggestions are displayed

- Snippet of `teacher`
- Snippet of `せんせい`

<details>
<summary>Snippets</summary>
<div>

```json
{
  "Teacher in Japanese": {
    "prefix": "せんせい",
    "body": "先生",
    "description": "先生: Teacher in Japanese"
  },
  "Teacher in English": {
    "prefix": "teacher",
    "body": "TEACHER",
    "description": "Teacher in English"
  },
  "Tabstop": {
    "prefix": "tabstop",
    "body": "test{$1}{$2}$0",
    "description": "test: Tabstops in snippet"
  }
}
```

</div>
</details>

### list of the characters immediately preceding the pattern in which suggestions are displayed

- Begining of line (Immediately after and after some whitespace characters)
- Tabstops in snippet
- Brakets (Immediately after each)

    ```
    {}[]()
    ```

- Ascii characters (Immediately after each)

    [*] Backslash is tested as double-backslash

    ```
    '`"#$%&=~^|<>;:,.!?/\\@+*_
    ```

- Multi-byte brakets (Immediately after each)

    ```
    ｛｝（）［］「」
    ```

- Multi-byte characters (Immediately after each)

    ```
    、。，．！？＃＄％＆＝～＾｜＜＞；：・￥＠＿＋＊
    ```

- Strings (Immediately after and after a whitespace)

    [**] Alphabet, Arabic numeral, Full-width alphabet, Full-width arabic numeral, Hiragana, Katakana, Kanji

    ```
    alphabet
    123
    ａｌｐｈａｂｅｔ
    １２３
    ひらがな
    カタカナ
    漢字
    ```

- Full-width space (Immediately after and after a whitespace characters)

    ```
    　
    ```

<details>
<summary>Complete file for testing</summary>
<div>

```latex
% Snippet of `teacher'
% Snippet of `せんせい'
%% IntelliSense starting with `\'
%% IntelliSense starting with `@'
%% IntelliSense starting with `**'
%% IntelliSense starting with `__'
%% IntelliSense starting with `...'
\documentclass{article}
\begin{document}

{}
[]
()
｛｝
（）
［］
「」
'
`
"
#
$ $
%
&
=
~
^
|
<
>
;
:
,
.
!
?
/
\\
@
+
*
_

、
。
，
．
！
？
＃
＄
％
＆
＝
～
＾
｜
＜
＞
；
：
・
￥
＠
＿
＋
＊

alphabet
123
ａｌｐｈａｂｅｔ
１２３
ひらがな
カタカナ
漢字
　

\end{document}
```


</div>
</details>

## About LaTeX Workshop's IntelliSense

I have also accidentally tested LaTeX Workshop's IntelliSense, so I am writing alongside it.

LaTeX Workshop's intelligences are as follows:

- IntelliSense provided by LaTeX Workshop
    - Starting with `\`
    - Starting with `@`
    -  `**`
    -  `__`
    -  `...`

The results of the suggestion display were in addition to the results above:

- Suggestion of IntelliSense provided by LaTeX Workshop
    - [x] IntelliSense starting with `\` and `@` works fine.
    - [ ] `**` and `__` and `...` did not show suggestion in every situation.
        - It will be displayed when you press `Ctrl+Space`.
        - In ver. 8.23.0, suggestions are displayed everywhere.

**Comment by jlelong** [comment]
Thank you so much for your very thorough tests and detailed report.

>  `**` and `__` and `...` did not show suggestion in every situation.

This is because we do not use the same `wordPattern` in vscode-latex-basics and in LaTeX-Workshop. In LaTeX-Workshop, we add `(**|__|\.\.\.)` to the `wordPattern` to make sure these snippets show up automatically, see https://github.com/jlelong/LaTeX-Workshop/commit/e0ba934c9e0457861ce463c43a13deb9a34e4577. If you want to test it inside LaTeX-Workshop, the simplest approach is to directly edit `~\.vscode\extensions\james-yu.latex-workshop-8.23.0\syntax\latex-language-configuration.json` because running the git version of LaTeX-Workshop requires `npm` (see https://github.com/James-Yu/LaTeX-Workshop/blob/master/CONTRIBUTING.md)

**Pull request merged**
